## Numpy
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. 

### a] Arrays
A numpy array is a grid of values, all of the same data type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

### How to create a numpy array ?
There are multiple ways to create a numpy array. One of the most common ways is to create one from a list or a list like an object by passing it to the np.array function.

#### Let's First Focus on 1-d Array

In [75]:
# 1. To Create an 1d array from a list

import numpy as np
list_1 = [0, 1, 2, 3, 4, 5]
arr_1d = np.array(list_1)
print(arr_1d)

[0 1 2 3 4 5]


In [ ]:
# 2. To Print the the type of the array
print(type(arr_1d))   #> class 'numpy.ndarray'

In [76]:
# 3. To Print the shape of the array 
print(arr_1d.shape)

(6,)


In [77]:
# 4. To Print the size of the array 
print(arr_1d.size)

6


In [ ]:
# 5. To Print dtype
print(arr_1d.dtype)

#### NOTE:
Difference between `type` and `dtype`
1. `type` is just tells what type of Python object is this.
2. `dtype` describes how the bytes in the fixed-size block of memory corresponding to an array.

In [78]:
# 6. To Print dimension of the array
print(arr_1d.ndim)

1


In [52]:
# 7. DataType Conversion
arr1d_f = np.array([11.7, 12, 13.5, 14, 15.3, 16], dtype='float')   # Another way to create an array
print(arr1d_f)

# Convert to 'int' datatype
arr1d_int = arr1d_f.astype('int')
print(arr1d_int)

# Convert to float then to str datatype
arr1d_str = arr1d_int.astype('float').astype('str')
print(arr1d_str)

[11.7 12.  13.5 14.  15.3 16. ]
[11 12 13 14 15 16]
['11.0' '12.0' '13.0' '14.0' '15.0' '16.0']


In [ ]:
# 8. Convert an array back to a list
arr1d_int.tolist()     

#### NOTE:
Difference between `python array` and `python lists`
    1. Arrays support vectorised operations, while lists don’t. 
    For example , you can divide an array by 3, and each number in the array will be divided by 3 and the result will be printed if you request it. If you try to divide a list by 3, Python will tell you that it can't be done, and an error will be thrown.
    2. Once an array is created, you cannot change its size. You will have to create a new array or overwrite the existing one.
    3. Every array has one and only one dtype. All items in it should be of that dtype whereas List can use different dtype elements.
    4. An equivalent numpy array occupies much less space than a python list of lists.

In [107]:
# 9. Reshape
a = np.array([[1,2,3,8,4,12],[4,5,6,9,13,14]])
print(a)
b = a.reshape(3,4) 
print(b)
c = a.reshape(-1,2)
print(c)

[[ 1  2  3  8  4 12]
 [ 4  5  6  9 13 14]]
[[ 1  2  3  8]
 [ 4 12  4  5]
 [ 6  9 13 14]]
[[ 1  2]
 [ 3  8]
 [ 4 12]
 [ 4  5]
 [ 6  9]
 [13 14]]


#### Now let's jump to 2-d array

In [54]:
import numpy as np

# 1. To Create a 2d array with 3 rows and 5 columns
list_2 = [[1, 2, 3, 4, 5],[3, 4, 5, 6, 7], [5, 6, 7, 8, 9]]
arr_2d = np.array(list_2, dtype='int')
print(arr_2d)

[[1 2 3 4 5]
 [3 4 5 6 7]
 [5 6 7 8 9]]


In [ ]:
## NOTE: Try out everything ONE - BY - ONE to understand well

# 2. To Print the type of the array
print(type(arr_2d))

# 3. To Print the shape of the array
print(arr_2d.shape)

# 4. To Print the size of the array 
print(arr_2d.size)

# 5. To Print dtype
print(arr_2d.dtype)

# 6. To Print dimension of the array
print(arr_2d.ndim)

# 7. DataType Conversion
# Convert to 'float' datatype
arr_2d_f = arr_2d.astype('float')
print(arr_2d_f)

# Convert to int then to str datatype
arr1d_str = arr_2d_f.astype('float').astype('str')
print(arr1d_str)

# 8. Convert an array back to a list
arr_2d.tolist()   

#### Numpy built-in functions to  create arrays:

In [1]:
import numpy as npy

# 1. To Create an 2-D array of all zeros
a = npy.zeros((2,2))   
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

[[0. 0.]
 [0. 0.]]


In [46]:
# 2. To Create an 2-D array of all ones
b = npy.ones((1,2))    
print(b)              # Prints "[[ 1.  1.]]"

[[1. 1.]]


In [10]:
# 3. To Create a constant array
c = npy.full((2,2), 7) 
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

[[7 7]
 [7 7]]


In [ ]:
# 4. To Create a 2x2 identity matrix
d = npy.eye(2)         
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

In [ ]:
# 5. To Create an array filled with random values
e = npy.random.random((2,2))  
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

In [42]:
# 6. To Create an 1-D array using arange method
f = npy.arange(2,7)     
print(f)

## NOTE:
# 1. This method takes the start index of the array, the end index, and the step size (which is optional)
# 2. The above script will return a NumPy 1-D array of size 5 with the elements 2, 3, 4, 5, and 6

[2 3 4 5 6]


1

In [48]:
# 7. To create an array with equally spaced elements using linspace Method
g = npy.linspace(1,5,7)
print(g)        



[1.         1.66666667 2.33333333 3.         3.66666667 4.33333333
 5.        ]


In [5]:
# 8 . To create an empty array
h = npy.empty([3,3])   
print(h)

## Note:
#  It does not set the array values to zero 
#  It will create the array of 3 x 3 dimension with random numbers

[[4.68895945e-310 6.94609582e-310 6.94609602e-310]
 [6.94609603e-310 6.94609602e-310 6.94609602e-310]
 [6.94609602e-310 6.94609602e-310 6.94609602e-310]]


In [7]:
# 9 . To create an empty array like shape of other array
i = npy.empty_like(h)   
print(i)

[[4.68895945e-310 6.94609582e-310 6.94609602e-310]
 [6.94609603e-310 6.94609602e-310 6.94609602e-310]
 [6.94609602e-310 6.94609602e-310 6.94609602e-310]]


In [8]:
# 10. To create an array with equally spaced elements using logspace Method
j = npy.logspace(1,5,7)
print(j)        

## Note::
# start ==> 10^1 & end ==> 10^5 with 7 values.Here 10 is the default base
# if you want to change the base to 2
# TRY this one too:: j = npy.logspace(1,5, num =7, base =2)

[1.00000000e+01 4.64158883e+01 2.15443469e+02 1.00000000e+03
 4.64158883e+03 2.15443469e+04 1.00000000e+05]


In [15]:
# 11. There is a full_like method similar to empty_like
k = npy.full_like(c, 13 )  
print(k)

[[13 13]
 [13 13]]


In [34]:
# 12. How to use shuffle method for initialization
a = npy.array([[1,2,3,4,5], [5,6,7,8,9], [9,10,11,12,13]])
npy.random.shuffle(a)
print(a)

##Note
# 1.numpy.random.shuffle() method doesn't return any values(i.e)==>(returns nothing(NONE))
# 2. if the data is multi dimensional array, it only shuffles along the first axis.

[[ 9 10 11 12 13]
 [ 1  2  3  4  5]
 [ 5  6  7  8  9]]


### b] Array Indexing
Numpy offers several ways to index into arrays.
##### How to access, Split and stack the numpy data structure

### Array indexing with 1-D and 2-D Arrays
In order to effectively use the NumPy arrays, it is very important to understand the way the arrays are indexed

In [43]:
# Indexing with 1-D Arrays

import numpy as np
x = np.arange(1,16)
print(x)       # It will print [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
print(x[0:8])  # It will print [1 2 3 4 5 6 7 8]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[1 2 3 4 5 6 7 8]


array([0, 1])

#### Slicing: 
Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:



In [ ]:
# Indexing with 2-D Arrays

import numpy as np

# Create the following rank 2 array with shape (3, 5)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4,5], [5,6,7,8,9], [9,10,11,12,13]])
print(a)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:5]
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"
print(a)

In [68]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
#Integer array indexing

import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

In [ ]:
#Boolean array indexing

import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

In [48]:
## Using SLICE Function
w = np.arange(10)
print(w)
x = slice(2,9,3)   #slice(start_value, end_value, step_size)
print(w[x])

## Same result without Slice Function :)
b = w[2:9:3]
print(b)

[0 1 2 3 4 5 6 7 8 9]
[2 5 8]
[2 5 8]


#### Stacking
Combining a definite numpy data structure

In [108]:
array2D_1 = [[1,2,3,4],[5,6,7,8]]
array2D_2 = [[9,10,11,12],[13,14,15,16]]

In [109]:
# Vstack (vertical stacking)
np.vstack((array2D_1, array2D_2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [110]:
# Hstack (Horizontal Stacking)
np.hstack((array2D_1, array2D_2))

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

#### Splitting

In [134]:
z = np.arange(16).reshape(4,4) 
np.split(z,[1,3])

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]

In [120]:
# VSplit (split in Vertical axis)
np.vsplit(z,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [135]:
# HSplit (split in Horizontal axis)
np.hsplit(z,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [141]:
# dSplit
y = np.arange(18).reshape(2,3,3)
np.dsplit(y,3)

## Note::
# dsplit only works on arrays of 3 or more dimensions

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]]])]

### c] Array Math
Basic mathematical functions operate elementwise on arrays 
    * Arithmetic Operations with NumPy Arrays
    * Linear Algebra Operations with NumPy Arrays

In [69]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype= 'float')
y = np.array([[5,6],[7,8]], dtype= 'float')


In [ ]:
# 1. To-Do Elementwise sum
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))


In [70]:
# 2. To-Do Elementwise difference
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [71]:
# 3. To-Do Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:
# 4. To-Do Elementwise division
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# 5. To-Do Elementwise square root
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

In [ ]:
# 6. To-Do  inner products of vectors,  to multiply a vector by a matrix & Matrix Multipliaction
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

In [142]:
# 7. One of the most useful functions for performing computations on arrays is sum:

import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [ ]:
# 8. To compute transpose of a matrix

import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

In [77]:
# 9. To compute inverse of a matrix

import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(np.linalg.inv(x))  # Prints "[[-2. 1.]
                         #          [1.5 -0.5]]"

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [78]:
# 10. To compute Determinant of a matrix

import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(np.linalg.det(x))  # Prints " -2.0000000000000004 "

[[1 2]
 [3 4]]
-2.0000000000000004


In [80]:
# 11. To compute trace of a matrix

import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(np.trace(x))  # Prints " 5 "

## NOTE:
# The sum of the diagonal elements of the matrix X is 1 + 4 = 5

[[1 2]
 [3 4]]
5


In [73]:
# 12. To find min and max value in an array

import numpy as np

z = np.random.randint(1,100,10)
print(z)

xmin = z.min()  
print(xmin)

xmax = z.max()  
print(xmax)  

##Note
# SEED Generator ==> numpy.random.randint(1,10)

[16 65 29 90 94 30  9 74  1 41]
1
94
None


In [63]:
# 13. To-Do Elementwise Log

import numpy as np

x = np.array([[1,2],[3,4]])
print(np.log(x))

[[0.         0.69314718]
 [1.09861229 1.38629436]]


In [ ]:
# 14. To-Do Elementwise exp

import numpy as np

x = np.array([[1,2],[3,4]])
print(np.exp(x))

In [ ]:
# 15. To-Do Elementwise sin

import numpy as np

x = np.array([[1,2],[3,4]])
print(np.sin(x))

In [144]:
# 16. To-Do Compute arithmetic mean

x = np.array([[1,2],[3,4]])
print(np.mean(x))
print(np.mean(x, axis = 0))   #Compute mean of each column;
print(np.mean(x, axis = 1))   #Compute mean of each row;

2.5
[2. 3.]
[1.5 3.5]


In [157]:
# 17. Operation that return indices
x = np.array([1, 2, 9, 3, 4]) 
print(np.argmax(x))    # return index of max value
print(np.argmin(x))    # return index of min value
print(np.argsort(x))   # return index of sorted values (Default: ascending order)
print(np.where(x < 5))   # return indeices of where x < 5

2
0
[0 1 3 4 2]
(array([0, 1, 3, 4]),)


In [152]:
# 18. To-Do Compute Covariance
x = np.array([[9,2],[3,6]])
print(np.cov(x))

[[ 24.5 -10.5]
 [-10.5   4.5]]


In [158]:
# 19. To-Do Cumulative Sum
x = np.array([1, 2, 9, 3, 4]) 
print(np.cumsum(x))

[ 1  3 12 15 19]


In [159]:
# 20. To-Do Cumulative Prod
x = np.array([1, 2, 9, 3, 4]) 
print(np.cumprod(x))

[  1   2  18  54 216]


In [162]:
# 21. To-Do choose the indices
x = np.array([1, 2, 9, 3, 4]) 
print(np.choose([1,4], choices = x))

[2 4]


### d] Broadcasting
[Extensively used in Machine Learning]

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.


In [72]:
#For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

In [ ]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]

print(np.reshape(v, (3, 1)) * w)
print(v)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)

# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)